name: Update Posts

on:
  schedule:
    - cron: '0 6 * * *' # Runs every day at 06:00 UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate new posts
        run: npm run generate-posts

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/posts.json
          git commit -m "Auto-update posts" || echo "No changes to commit"
          git push
